<script type="application/javascript">
	function sendRequest(){
		$("#responseAPI").html("");
		if(validateData()){ return; }
		$("#responseAPI").html("<br/><i class='fa fa-refresh fa-spin fa-5x'></i>");
		settings.data.orgid = $("#orgid").val().trim();
		settings.data.email = $("#email").val().trim();
		settings.data.name  = $("#name" ).val().trim();
		$.ajax(settings)
			.done(function (tmp, response, xhr) { 
				var o = "";
				//--------------------------------------------------------
				o+= "<h2>Data:</h2>";
				o+="<pre>ID: "+xhr.responseJSON.id+"</pre>"; 
				//--------------------------------------------------------
				o+= "<h2>Response:</h2>";
				o+="<pre>"; 
				o+=JSON.stringify(xhr.responseJSON);
				o+="</pre>"; 
				//--------------------------------------------------------
				$("#responseAPI").html(o); 
			})
			.fail(function (xhr) { $("#responseAPI").text(xhr.status+": "+xhr.statusText); });
	}
</script>